# Generated by Django 6.1 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="message_color",
            field=models.CharField(
                choices=[
                    ("amber", "Янтарный"),
                    ("blue", "Ночной синий"),
                    ("sage", "Шалфейный"),
                    ("plum", "Сливовый"),
                ],
                default="amber",
                max_length=16,
            ),
        ),
    ]
