# Generated by Django 6.1 on 2026-09-25 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_last_seen_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushsubscription',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Подписка на уведомления', 'verbose_name_plural': 'Подписки на уведомления'},
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='auth',
            field=models.CharField(max_length=255, verbose_name='Секрет подписки'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='direct_messages_enabled',
            field=models.BooleanField(default=True, verbose_name='Уведомления о личных сообщениях'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Включена'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.URLField(max_length=1000, unique=True, verbose_name='Адрес push-службы'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='p256dh',
            field=models.CharField(max_length=255, verbose_name='Открытый ключ подписки'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ban_reason',
            field=models.CharField(blank=True, max_length=240, verbose_name='Причина блокировки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заблокирован'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Блокировка до'),
        ),
        migrations.AlterField(
            model_name='user',
            name='message_color',
            field=models.CharField(choices=[('amber', 'Янтарный'), ('blue', 'Ночной синий'), ('sage', 'Шалфейный'), ('plum', 'Сливовый')], default='amber', max_length=16, verbose_name='Цвет сообщений'),
        ),
        migrations.AlterField(
            model_name='user',
            name='welcome_pending',
            field=models.BooleanField(default=False, verbose_name='Ожидает приветствия'),
        ),
    ]
