# Generated by Django 6.1 on 2026-09-26 07:23

from django.db import migrations, models


def seed_statuses(apps, schema_editor):
    Status = apps.get_model("users", "ChatStatus")
    values = (
        ("reading", "Читаю, но не отвечаю"),
        ("eating", "Кушаю"),
        ("beer", "Пью пиво"),
        ("thinking", "Думаю"),
        ("smoking", "Ушёл курить"),
        ("back_soon", "Скоро вернусь"),
    )
    for position, (code, label) in enumerate(values):
        Status.objects.using(schema_editor.connection.alias).get_or_create(
            code=code, defaults={"label": label, "position": position},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_pushsubscription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=24, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=80, verbose_name='Название')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен для выбора')),
            ],
            options={
                'verbose_name': 'статус в чате',
                'verbose_name_plural': 'Статусы в чате',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.RunPython(seed_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='presence_status',
            field=models.CharField(blank=True, max_length=24, verbose_name='Статус в чате'),
        ),
    ]
