# Generated by Django 6.1 on 2026-09-26 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_chatstatus_alter_user_presence_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_blocks', to=settings.AUTH_USER_MODEL, verbose_name='Кто блокирует')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL, verbose_name='Заблокированный пользователь')),
            ],
            options={
                'verbose_name': 'персональная блокировка',
                'verbose_name_plural': 'Персональные блокировки',
                'constraints': [models.UniqueConstraint(fields=('owner', 'target'), name='unique_personal_block'), models.CheckConstraint(condition=models.Q(('owner', models.F('target')), _negated=True), name='no_self_personal_block')],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('abuse', 'Оскорбление или травля'), ('spam', 'Спам'), ('privacy', 'Личные данные'), ('other', 'Другое')], max_length=16, verbose_name='Причина')),
                ('details', models.CharField(blank=True, max_length=1000, verbose_name='Пояснение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассмотрено')),
                ('resolution_note', models.CharField(blank=True, max_length=1000, verbose_name='Решение и причина')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_user_reports', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_user_reports', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'жалоба на пользователя',
                'verbose_name_plural': 'Жалобы на пользователей',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('reporter', 'target'), name='one_open_user_report')],
            },
        ),
    ]
