# Generated by Django 6.1 on 2026-09-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_personalblock_userreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_status',
            field=models.CharField(blank=True, help_text='Короткая фраза вместо выбранного статуса. До 40 символов.', max_length=40, verbose_name='Свой статус'),
        ),
    ]
