# Generated by Django 6.1 on 2026-09-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_custom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_rules_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Правила приняты'),
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_rules_version',
            field=models.CharField(blank=True, max_length=16, verbose_name='Версия правил'),
        ),
    ]
