[tool.poetry]
name = "project-chat"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"
django = "^6.1"
channels = "^4.3.2"
channels-redis = "^4.3.0"
daphne = "^4.2.3"
pillow = "^12.3.0"
django-allauth = {version = "^65.19.1", extras = ["socialaccount"]}
pywebpush = "^2.1.2"
djangorestframework = "^3.18.0"
drf-spectacular = "^0.30.0"
celery = "^5.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "playwright (>=1.62.0,<2.0.0)"
]
