# Generated by Django 6.1 on 2026-08-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_public_rooms(apps, schema_editor):
    room_model = apps.get_model("chat", "Room")
    rooms = (
        ("У стойки", "u-stoyki", "Главный разговор: здесь Семён слышит всё."),
        ("Возле бильярда", "vozle-bilyarda", "Неформальные разговоры, игры и лёгкие споры."),
        ("Курилка", "kurilka", "Короткие реплики и разговоры между делом."),
        ("Подвал", "podval", "Код, логи и баги, которые лучше разбирать вместе."),
        ("После закрытия", "posle-zakrytiya", "Идеи, итоги и спокойные ночные разговоры."),
    )
    for name, slug, description in rooms:
        room_model.objects.get_or_create(
            slug=slug,
            defaults={
                "name": name,
                "description": description,
                "visibility": "public",
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_message_recipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_chat_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Открытая"), ("private", "Тайная")],
                default="public",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="RoomMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="chat.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="private_room_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomReadState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_read_at", models.DateTimeField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_states",
                        to="chat.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_read_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="private_chat_rooms",
                through="chat.RoomMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="roommembership",
            constraint=models.UniqueConstraint(
                fields=("room", "user"),
                name="unique_private_room_member",
            ),
        ),
        migrations.AddConstraint(
            model_name="roomreadstate",
            constraint=models.UniqueConstraint(
                fields=("room", "user"),
                name="unique_room_read_state",
            ),
        ),
        migrations.RunPython(create_public_rooms, migrations.RunPython.noop),
    ]
