# Generated by Django 6.1 on 2026-09-01 19:38

import chat.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=chat.models.note_attachment_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('image', 'Изображение'), ('file', 'Файл')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.note')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
