# Generated by Django 6.1 on 2026-09-09 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_messagereaction_emoji'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='visibility',
            field=models.CharField(choices=[('public', 'Открытая'), ('private', 'Закрытая')], default='public', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(condition=models.Q(('visibility', 'private')), fields=('owner',), name='one_owned_private_room_per_user'),
        ),
    ]
