# Generated by Django 6.1 on 2026-09-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_atmosphereline'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='kind',
            field=models.CharField(choices=[('image', 'Изображение'), ('file', 'Файл'), ('audio', 'Аудио')], max_length=10),
        ),
        migrations.AlterField(
            model_name='noteattachment',
            name='kind',
            field=models.CharField(choices=[('image', 'Изображение'), ('file', 'Файл'), ('audio', 'Аудио')], max_length=10),
        ),
    ]
