# Generated by Django 6.1 on 2026-09-25 17:07

import chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_seed_russian_pep20_drafts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atmosphereline',
            options={'ordering': ('kind', 'text'), 'verbose_name': 'Атмосферная строка', 'verbose_name_plural': 'Атмосферные строки'},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['created_at'], 'verbose_name': 'Вложение', 'verbose_name_plural': 'Вложения'},
        ),
        migrations.AlterModelOptions(
            name='bartenderjob',
            options={'ordering': ('-created_at',), 'verbose_name': 'Задание Семёна', 'verbose_name_plural': 'Задания Семёна'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'permissions': [('moderate_message', 'Can moderate chat messages')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='messagereaction',
            options={'verbose_name': 'Реакция', 'verbose_name_plural': 'Реакции'},
        ),
        migrations.AlterModelOptions(
            name='messagereport',
            options={'ordering': ('-created_at',), 'verbose_name': 'Жалоба', 'verbose_name_plural': 'Жалобы'},
        ),
        migrations.AlterModelOptions(
            name='moderationevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Событие модерации', 'verbose_name_plural': 'Журнал модерации'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AlterModelOptions(
            name='noteattachment',
            options={'ordering': ['created_at'], 'verbose_name': 'Вложение заметки', 'verbose_name_plural': 'Вложения заметок'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name'], 'verbose_name': 'Беседа', 'verbose_name_plural': 'Беседы'},
        ),
        migrations.AlterModelOptions(
            name='roommembership',
            options={'verbose_name': 'Участник беседы', 'verbose_name_plural': 'Участники бесед'},
        ),
        migrations.AlterModelOptions(
            name='roomreadstate',
            options={'verbose_name': 'Статус прочтения', 'verbose_name_plural': 'Статусы прочтения'},
        ),
        migrations.AddField(
            model_name='messagereport',
            name='outcome',
            field=models.CharField(blank=True, db_default='', choices=[('dismiss', 'Жалоба отклонена'), ('hide', 'Сообщение скрыто'), ('ban', 'Автор заблокирован')], max_length=16, verbose_name='Решение'),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='resolution_note',
            field=models.CharField(blank=True, db_default='', max_length=240, verbose_name='Комментарий к решению'),
        ),
        migrations.AlterField(
            model_name='atmosphereline',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Одобрено'),
        ),
        migrations.AlterField(
            model_name='atmosphereline',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_atmosphere_lines', to=settings.AUTH_USER_MODEL, verbose_name='Одобрил'),
        ),
        migrations.AlterField(
            model_name='atmosphereline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='atmosphereline',
            name='generated_by_model',
            field=models.CharField(blank=True, max_length=120, verbose_name='Модель генерации'),
        ),
        migrations.AlterField(
            model_name='atmosphereline',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='atmosphereline',
            name='kind',
            field=models.CharField(choices=[('semen', 'Реплика Семёна'), ('pep', 'Цитата PEP')], max_length=12, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='atmosphereline',
            name='source_label',
            field=models.CharField(blank=True, max_length=80, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='atmosphereline',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на источник'),
        ),
        migrations.AlterField(
            model_name='atmosphereline',
            name='status',
            field=models.CharField(choices=[('draft', 'На модерации'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], db_index=True, default='draft', max_length=12, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='atmosphereline',
            name='text',
            field=models.CharField(max_length=140, unique=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.CharField(max_length=100, verbose_name='Тип содержимого'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=chat.models.attachment_upload_to, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='kind',
            field=models.CharField(choices=[('image', 'Изображение'), ('file', 'Файл'), ('audio', 'Аудио')], max_length=10, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='original_name',
            field=models.CharField(max_length=255, verbose_name='Исходное имя файла'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='size',
            field=models.PositiveIntegerField(verbose_name='Размер в байтах'),
        ),
        migrations.AlterField(
            model_name='bartenderjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='bartenderjob',
            name='error_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='Код ошибки'),
        ),
        migrations.AlterField(
            model_name='bartenderjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='bartenderjob',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Личное обращение'),
        ),
        migrations.AlterField(
            model_name='bartenderjob',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bartender_question_jobs', to='chat.message', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='bartenderjob',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bartender_response_jobs', to='chat.message', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='bartenderjob',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bartender_jobs', to='chat.room', verbose_name='Беседа'),
        ),
        migrations.AlterField(
            model_name='bartenderjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начато'),
        ),
        migrations.AlterField(
            model_name='bartenderjob',
            name='status',
            field=models.CharField(choices=[('queued', 'В очереди'), ('started', 'Выполняется'), ('succeeded', 'Готово'), ('failed', 'Ошибка')], db_index=True, default='queued', max_length=12, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bartenderjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bartender_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='message',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Скрыто'),
        ),
        migrations.AlterField(
            model_name='message',
            name='hidden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Скрыл'),
        ),
        migrations.AlterField(
            model_name='message',
            name='hidden_reason',
            field=models.CharField(blank=True, max_length=240, verbose_name='Причина скрытия'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message', verbose_name='Ответ на сообщение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.room', verbose_name='Беседа'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='emoji',
            field=models.CharField(choices=[('👍', 'Нравится'), ('👎', 'Не нравится'), ('❤️', 'Любовь'), ('😂', 'Смешно'), ('🔥', 'Огонь'), ('😮', 'Удивлён'), ('😢', 'Грустно'), ('🤔', 'Задумался'), ('🤝', 'Согласен'), ('🎉', 'Праздную')], max_length=8, verbose_name='Эмодзи'),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='messagereport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='messagereport',
            name='details',
            field=models.CharField(blank=True, max_length=240, verbose_name='Пояснение'),
        ),
        migrations.AlterField(
            model_name='messagereport',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='messagereport',
            name='reason',
            field=models.CharField(choices=[('abuse', 'Оскорбление или травля'), ('spam', 'Спам или реклама'), ('privacy', 'Личные данные'), ('other', 'Другое')], max_length=16, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='messagereport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reports', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='messagereport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Рассмотрено'),
        ),
        migrations.AlterField(
            model_name='messagereport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_message_reports', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел'),
        ),
        migrations.AlterField(
            model_name='moderationevent',
            name='action',
            field=models.CharField(choices=[('resolve_report', 'Рассмотрение жалоб'), ('ban', 'Блокировка'), ('unban', 'Разблокировка'), ('hide_message', 'Скрытие сообщения'), ('restore_message', 'Восстановление сообщения')], max_length=20, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='moderationevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='moderationevent',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Действует до'),
        ),
        migrations.AlterField(
            model_name='moderationevent',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events', to='chat.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='moderationevent',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AlterField(
            model_name='moderationevent',
            name='reason',
            field=models.CharField(blank=True, max_length=240, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='moderationevent',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='note',
            name='source_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_notes', to='chat.message', verbose_name='Исходное сообщение'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='noteattachment',
            name='content_type',
            field=models.CharField(max_length=100, verbose_name='Тип содержимого'),
        ),
        migrations.AlterField(
            model_name='noteattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='noteattachment',
            name='file',
            field=models.FileField(upload_to=chat.models.note_attachment_upload_to, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='noteattachment',
            name='kind',
            field=models.CharField(choices=[('image', 'Изображение'), ('file', 'Файл'), ('audio', 'Аудио')], max_length=10, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='noteattachment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.note', verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='noteattachment',
            name='original_name',
            field=models.CharField(max_length=255, verbose_name='Исходное имя файла'),
        ),
        migrations.AlterField(
            model_name='noteattachment',
            name='size',
            field=models.PositiveIntegerField(verbose_name='Размер в байтах'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Адрес беседы'),
        ),
        migrations.AlterField(
            model_name='room',
            name='visibility',
            field=models.CharField(choices=[('public', 'Открытая'), ('private', 'Закрытая')], default='public', max_length=10, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='roommembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Присоединился'),
        ),
        migrations.AlterField(
            model_name='roommembership',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.room', verbose_name='Беседа'),
        ),
        migrations.AlterField(
            model_name='roommembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_room_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='roomreadstate',
            name='last_read_at',
            field=models.DateTimeField(verbose_name='Прочитано до'),
        ),
        migrations.AlterField(
            model_name='roomreadstate',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='chat.room', verbose_name='Беседа'),
        ),
        migrations.AlterField(
            model_name='roomreadstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_states', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность в мс'),
        ),
        migrations.AlterField(
            model_name='note',
            name='source_author',
            field=models.CharField(blank=True, max_length=150, verbose_name='Автор исходного сообщения'),
        ),
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='private_chat_rooms', through='chat.RoomMembership', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
