# Generated by Django 6.1 on 2026-09-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_alter_atmosphereline_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereaction',
            name='emoji',
            field=models.CharField(choices=[('👍', 'Нравится'), ('👎', 'Не нравится'), ('❤️', 'Любовь'), ('😂', 'Смешно'), ('🔥', 'Огонь'), ('😮', 'Удивлён'), ('😢', 'Грустно'), ('🤔', 'Задумался'), ('🤝', 'Согласен'), ('🎉', 'Праздную'), ('😍', 'В восторге'), ('😎', 'Круто'), ('🙏', 'Спасибо'), ('👏', 'Аплодисменты'), ('💯', 'Точно'), ('🤯', 'Взрыв мозга')], max_length=8, verbose_name='Эмодзи'),
        ),
    ]
