# Generated by Django 6.1 on 2026-09-29 20:41

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_expand_reaction_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to=chat.models.attachment_thumbnail_upload_to, verbose_name='Превью'),
        ),
        migrations.AddField(
            model_name='noteattachment',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to=chat.models.note_attachment_thumbnail_upload_to, verbose_name='Превью'),
        ),
    ]
