# Generated by Django 6.1 on 2026-09-29 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_attachment_thumbnails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'created_at'], name='msg_room_created_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'created_at'], name='msg_recipient_created_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereport',
            index=models.Index(fields=['resolved_at'], name='report_resolved_idx'),
        ),
    ]
